---
- hosts: all
  vars_files:
    - vars/default.yml

  tasks:
    - name: Login to AWS ECR
      no_log: True
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login \
          --username=AWS \
          {{ aws_user_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com \
          --password-stdin
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    - name: Pull lw-server Docker image
      shell: docker pull {{ aws_user_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ docker_image }}:latest

    - name: Stop container
      shell: ID=$(docker ps | grep {{ docker_image }} | awk '{print $1}') && [ ! -z $ID ] && docker stop $ID

    - name: Restart it
      community.general.supervisorctl:
        name: '{{ docker_image }}'
        state: started

    - name: Remove dangling images
      shell: docker images | grep "<none>" | awk '{print $3}' | xargs -r docker rmi -f
