name: Build web deployment

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies with pnpm
        uses: ./.github/actions/pnpm

      - name: Build the packages
        run: |
          pnpm --filter types --filter prototypes build

      - name: Run tests
        run: pnpm -r test

      - name: Build the GitHub pages distribution
        run: pnpm --filter client build
        env:
          VITE_WS_URL: wss://tic-tac-5-api.fly.dev/
          VITE_API_URL: https://api.teemukoivisto.xyz/tic-tac-5

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: tic-tac-5
          directory: ./packages/client/dist
